apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-app-manual
spec:
  selector:
    matchLabels:
      app: logging-app-manual
  template:
    metadata:
      labels:
        app: logging-app-manual
    spec:
      containers:
      - name: filebeat
        image: elastic/filebeat:7.14.2
        args: [
            "-c", "/etc/filebeat/filebeat.yaml",
            "-e"
        ]
        volumeMounts:
            - name: beat-manual-config
              mountPath: /etc/filebeat/
            - name: manual-log-directory
              mountPath: /tmp/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: logging-app-manual
        image: sladesoftware/log-application:latest
        volumeMounts:
          - name: manual-log-directory
            mountPath: /tmp/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: beat-manual-config
          configMap:
            name: filebeat-pipeline
            items:
              - key: filebeat.yaml
                path: filebeat.yaml
        - name: manual-log-directory
          emptyDir: {}
